### ISSUE TITLE
ssb

### ISSUE THREAD

**Issue by ahdinosaur** [peacekeeper/blockchain-identity#1]
hey @peacekeeper,

some [friends of mine](https://github.com/ssbc) are working on blockchain identities through a user-facing app called [Patchwork](https://ssbc.github.io/patchwork/) based on a peer-to-peer "blockchain" database called [Scuttlebot](https://scuttlebot.io/).

the full overview of the "blockchain identity" protocol is [here](https://scuttlebot.io/more/protocols/secure-scuttlebutt.html). personally i appreciate this "blockchain identity" protocol much more than the usual [singleton-based approach](https://scuttlebot.io/more/articles/design-challenge-avoid-centralization-and-singletons.html). it has an interesting trait of embracing subjectivity over consensus, so for example there is no global registry of names to id mappings, rather each identity can publish messages that map their favorite pet name mappings for themselves and others.

just thought i'd share, have a good one. :smile:

**Comment by peacekeeper** [comment]
thanks @ahdinosaur this looks really interesting with some very creative and different ideas.. i just added it to the list, i'll also install it and give it a try! :)
