### ISSUE TITLE
Add https://onekosmos.com/

### ISSUE THREAD

**Issue by peacekeeper** [peacekeeper/blockchain-identity#31]

**Comment by rohanpinto** [comment]
**[1Kosmos](https://onekosmos.com)** revolutionizes identity management, enabling people and companies to escape from the legacy systems of paper-based documents and move into a true digital identity with unprecedented privacy, security, transparency and individual rights by leveraging the power of [blockchain technology](https://onekosmos.com/wp-content/uploads/2018/04/1Kosmos_BlockID_OnePager.pdf). The Flagship product called **[BlockID](https://onekosmos.com/product-details/)**, would enable users to have a frictionless experience authenticating into web applications _(with their self sovereign verified trusted digital identity)_ and also [windows desktops](https://onekosmos.com/blockid-hello/) using inApp biometrics like face, voice or thumbprint. BlockID is also NIST 800-63-3 compliant with IAL, AAL & FAL adherence.

**Comment by peacekeeper** [comment]
Thanks for the suggestion, but this is meant to be a neutral and objective list, not a place for advertising speak :)

**Comment by rohanpinto** [comment]
Got it. I didn't intend it to be advertising speak.

**Comment by peacekeeper** [comment]
Just added BlockID / 1Kosmos to the list with slightly different language, let me know if you disagree!
