### ISSUE TITLE
Add http://signd.id/

### ISSUE THREAD

**Issue by peacekeeper** [peacekeeper/blockchain-identity#58]

**Comment by nembal** [comment]
Markus, this is a very strange website with no correlation to identity. Is
it only project name perhaps?
/ https://signd.io/ that seems like a telco ID project.

Balázs Némethi

**Comment by peacekeeper** [comment]
Sorry I posted the wrong URL at first. https://signd.id/ is correct.

**Comment by peacekeeper** [comment]
Fixed by 29d98c0a9d9e17b4634c4d740a1feb6f5cce4508
