### ISSUE TITLE
additions

### ISSUE THREAD

**Issue by jimscarver** [peacekeeper/blockchain-identity#6]
Great resource. thanks. you might want to add

civic.com - Through our decentralized architecture with the blockchain and biometrics on the mobile device, our platform provides multi-factor authentication without a username, password, third party authenticator, or physical hardware token. (Not open source but free basic service.)

Fermat.org (also IoPgo.com) - Internet of People (IoP) offers the world’s only infrastructure with an open social graph, direct access to people and direct device to device communication. 

internetidentityworkshop.com (IIW) "the woodstock of identity". Are you going to iiw24 mar 2-4 mountain view CA?

**Comment by peacekeeper** [comment]
Hello Jim, great input, thanks. I just added Fermat and Civic. Yes I will be at IIW, would be nice to meet you there!
